### ISSUE TITLE
Is this be worked on

### ISSUE THREAD

**Issue by MichaelJmad** [Elmotrix/StationeersZoop#1]
I was linked to this regarding a mod request I had "Click and drag building?
for at least wire and pipe networks or ultimately wire, pipe, frames, etc."
If this is the case any idea when a release may be?

P.S. Love the network painter

**Comment by Elmotrix** [comment]
this is currently abandoned.

**Comment by MichaelJmad** [comment]
Shame I was really looking forward to a mod like that :(
